// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouSearch.Infra.Configuracao.EFCore;

namespace YouSearch.Infra.Migrations
{
    [DbContext(typeof(AplicacaoContexto))]
    partial class AplicacaoContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YouSearch.Dominio.Entidades.PageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("resultsPerPage");

                    b.Property<int>("totalResults");

                    b.HasKey("Id");

                    b.ToTable("PageInfo");
                });

            modelBuilder.Entity("YouSearch.Dominio.Entidades.SearchResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ETag");

                    b.Property<string>("Kind");

                    b.Property<int?>("SnippetId");

                    b.HasKey("Id");

                    b.HasIndex("SnippetId");

                    b.ToTable("SearchResponse");
                });

            modelBuilder.Entity("YouSearch.Dominio.Entidades.SearchResultSnippet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChannelId");

                    b.Property<string>("ChannelTitle");

                    b.Property<string>("Description");

                    b.Property<string>("ETag");

                    b.Property<string>("LiveBroadcastContent");

                    b.Property<DateTime?>("PublishedAt");

                    b.Property<string>("PublishedAtRaw");

                    b.Property<int?>("ThumbnailsId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ThumbnailsId");

                    b.ToTable("SearchResultSnippet");
                });

            modelBuilder.Entity("YouSearch.Dominio.Entidades.Thumbnail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ETag");

                    b.Property<long?>("Height");

                    b.Property<string>("Url");

                    b.Property<long?>("Width");

                    b.HasKey("Id");

                    b.ToTable("Thumbnail");
                });

            modelBuilder.Entity("YouSearch.Dominio.Entidades.ThumbnailDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Default__Id");

                    b.Property<string>("ETag");

                    b.Property<int?>("HighId");

                    b.Property<int?>("MaxresId");

                    b.Property<int?>("MediumId");

                    b.Property<int?>("StandardId");

                    b.HasKey("Id");

                    b.HasIndex("Default__Id");

                    b.HasIndex("HighId");

                    b.HasIndex("MaxresId");

                    b.HasIndex("MediumId");

                    b.HasIndex("StandardId");

                    b.ToTable("ThumbnailDetails");
                });

            modelBuilder.Entity("YouSearch.Dominio.Entidades.SearchResponse", b =>
                {
                    b.HasOne("YouSearch.Dominio.Entidades.SearchResultSnippet", "Snippet")
                        .WithMany()
                        .HasForeignKey("SnippetId");
                });

            modelBuilder.Entity("YouSearch.Dominio.Entidades.SearchResultSnippet", b =>
                {
                    b.HasOne("YouSearch.Dominio.Entidades.ThumbnailDetails", "Thumbnails")
                        .WithMany()
                        .HasForeignKey("ThumbnailsId");
                });

            modelBuilder.Entity("YouSearch.Dominio.Entidades.ThumbnailDetails", b =>
                {
                    b.HasOne("YouSearch.Dominio.Entidades.Thumbnail", "Default__")
                        .WithMany()
                        .HasForeignKey("Default__Id");

                    b.HasOne("YouSearch.Dominio.Entidades.Thumbnail", "High")
                        .WithMany()
                        .HasForeignKey("HighId");

                    b.HasOne("YouSearch.Dominio.Entidades.Thumbnail", "Maxres")
                        .WithMany()
                        .HasForeignKey("MaxresId");

                    b.HasOne("YouSearch.Dominio.Entidades.Thumbnail", "Medium")
                        .WithMany()
                        .HasForeignKey("MediumId");

                    b.HasOne("YouSearch.Dominio.Entidades.Thumbnail", "Standard")
                        .WithMany()
                        .HasForeignKey("StandardId");
                });
#pragma warning restore 612, 618
        }
    }
}
